FROM golang:1.11-alpine AS builder

WORKDIR /app

COPY ./reception ./reception
COPY ./kit ./kit

RUN apk add --update bash make git gcc libc-dev
RUN cd ./reception && make

# ---

FROM alpine

COPY --from=builder /app/reception/dist/reception /

EXPOSE 8080
ENTRYPOINT ["/reception"]
