// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Created struct {
	ID                   string       `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CustomerName         string       `protobuf:"bytes,2,opt,name=CustomerName,proto3" json:"CustomerName,omitempty"`
	Items                []*OrderItem `protobuf:"bytes,3,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Created) Reset()         { *m = Created{} }
func (m *Created) String() string { return proto.CompactTextString(m) }
func (*Created) ProtoMessage()    {}
func (*Created) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{0}
}

func (m *Created) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Created.Unmarshal(m, b)
}
func (m *Created) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Created.Marshal(b, m, deterministic)
}
func (m *Created) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Created.Merge(m, src)
}
func (m *Created) XXX_Size() int {
	return xxx_messageInfo_Created.Size(m)
}
func (m *Created) XXX_DiscardUnknown() {
	xxx_messageInfo_Created.DiscardUnknown(m)
}

var xxx_messageInfo_Created proto.InternalMessageInfo

func (m *Created) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Created) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *Created) GetItems() []*OrderItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type OrderItem struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Size                 string   `protobuf:"bytes,2,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{1}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OrderItem) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func init() {
	proto.RegisterType((*Created)(nil), "order.Created")
	proto.RegisterType((*OrderItem)(nil), "order.OrderItem")
}

func init() { proto.RegisterFile("proto/order.proto", fileDescriptor_f65b0626cc3aada8) }

var fileDescriptor_f65b0626cc3aada8 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2f, 0x4a, 0x49, 0x2d, 0xd2, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x1c, 0xa5, 0x54,
	0x2e, 0x76, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x14, 0x21, 0x3e, 0x2e, 0x26, 0x4f, 0x17, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x26, 0x4f, 0x17, 0x21, 0x25, 0x2e, 0x1e, 0xe7, 0xd2, 0xe2,
	0x92, 0xfc, 0xdc, 0xd4, 0x22, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0xb0, 0x0c, 0x8a, 0x98, 0x90,
	0x1a, 0x17, 0xab, 0x67, 0x49, 0x6a, 0x6e, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x80,
	0x1e, 0xc4, 0x0a, 0x7f, 0x10, 0x09, 0x92, 0x08, 0x82, 0x48, 0x2b, 0x19, 0x73, 0x71, 0xc2, 0xc5,
	0x84, 0x84, 0xb8, 0x58, 0x42, 0x2a, 0x0b, 0x52, 0xa1, 0x56, 0x81, 0xd9, 0x20, 0xb1, 0xe0, 0xcc,
	0x2a, 0x98, 0x25, 0x60, 0xb6, 0x13, 0x6f, 0x14, 0x37, 0x92, 0xbb, 0x93, 0xd8, 0xc0, 0x1c, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x9b, 0x70, 0xbf, 0xcd, 0x00, 0x00, 0x00,
}
