// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order.proto

package order

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Created struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Items                []string `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Created) Reset()         { *m = Created{} }
func (m *Created) String() string { return proto.CompactTextString(m) }
func (*Created) ProtoMessage()    {}
func (*Created) Descriptor() ([]byte, []int) {
	return fileDescriptor_f65b0626cc3aada8, []int{0}
}

func (m *Created) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Created.Unmarshal(m, b)
}
func (m *Created) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Created.Marshal(b, m, deterministic)
}
func (m *Created) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Created.Merge(m, src)
}
func (m *Created) XXX_Size() int {
	return xxx_messageInfo_Created.Size(m)
}
func (m *Created) XXX_DiscardUnknown() {
	xxx_messageInfo_Created.DiscardUnknown(m)
}

var xxx_messageInfo_Created proto.InternalMessageInfo

func (m *Created) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Created) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Created)(nil), "order.Created")
}

func init() { proto.RegisterFile("proto/order.proto", fileDescriptor_f65b0626cc3aada8) }

var fileDescriptor_f65b0626cc3aada8 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2f, 0x4a, 0x49, 0x2d, 0xd2, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x1c, 0x25, 0x7d,
	0x2e, 0x76, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x14, 0x21, 0x3e, 0x2e, 0x26, 0x4f, 0x17, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x26, 0x4f, 0x17, 0x21, 0x11, 0x2e, 0x56, 0xcf, 0x92, 0xd4,
	0xdc, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x08, 0xc7, 0x89, 0x37, 0x8a, 0x1b, 0xc9,
	0xb0, 0x24, 0x36, 0x30, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x50, 0xcd, 0x69, 0xd9, 0x62,
	0x00, 0x00, 0x00,
}
